name: Pull Request To Dev
run-name: Run Integration Tests
on:
  push:
    branches:
      - '0071'
jobs:
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run app
        run: python3 ./hello.app/app.py &
      - name: Run tests
        run: |
          chmod +x ./test/data.sh
          ./test/data.sh
